### ISSUE TITLE
cannot upgrate gefpy from 0.1.0 to >=0.1.1 

### ISSUE THREAD

**Issue by ChenddatHKU** [BGIResearch/gefpy#1]
Hi Zhibo,

I cloned Stereopy form https://github.com/BGIResearch/stereopy, then installed the required packed locally (pycharm). Default installation was gefpy 0.1.0, how system warned requirement for gefpy>=0.1.1. Failure always reminded, nomatter installed from pycharm or pin from the terminal. 
Thus, may I ask do you have any suggestions for this.
![Uploading Screenshot 2022-01-11 at 9.28.35 AM.png…]()

**Comment by huangzhibo** [comment]
Hi ChenddatHKU, 
Do you use the mac system? 
Now you can try again.

**Comment by ChenddatHKU** [comment]
Yes, mac system was used.
Gefpy updating issue fixed now. 
Much appreciated Zhibo.
