### ISSUE TITLE
/pip-req-build-yqrplduo/gefpy/gene_exp_cy.cpp:742:10: fatal error: gef.h: No such file or directory

### ISSUE THREAD

**Issue by YiningSun** [BGIResearch/gefpy#10]
Downloaded the zip file from here and tried to build gefpy by using pip install gefpy-master.zip, failed at setup.py due to "/tmp//pip-req-build-yqrplduo/gefpy/gene_exp_cy.cpp:742:10: fatal error: gef.h: No such file or directory"

As you can tell coding is not my profession, just hope someone could help, thank you (couldn't do git clone due to connection issues).

**Comment by jasonborn** [comment]
gefpy is a thin, pythonic wrapper around geftools.  you can use  "pip install gefpy" to install gefpy.Gook Luck!

**Comment by jasonborn** [comment]
> 

gefpy is a thin, pythonic wrapper around geftools. you can use "pip install gefpy" to install gefpy.Gook Luck!
